app:
  title: Scaffolded Backstage App
  baseUrl: http://0.0.0.0:3000

organization:
  name: My Company

backend:
  baseUrl: http://54.158.231.168:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://54.158.231.168:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: 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

proxy:

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/python-service/template.yaml
      rules:
        - allow: [Template] 

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/branch-protection/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/create_pull_req/template.yaml
      rules:
        - allow: [Template]  

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/ms-teams/template.yaml
      rules:
        - allow: [Template] 

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/custom-action/template.yaml
      rules:
        - allow: [Template] 

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/aws-resource-create/template.yaml
      rules:
        - allow: [Template] 

    - type: file
      target: /home/ubuntu/backstage/my-backstage-app/templates/shell-command/template.yaml
      rules:
        - allow: [Template] 

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
  useUrlReadersSearch: true

kubernetes:

permission:
  enabled: true
